Algoritmo "Calculo de KM"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
litro:inteiro
km:inteiro
resposta:inteiro
Inicio
escreval("qual a quantidade de km da viagem?")
leia(km)
escreval("quantos km por litro o automovel gasta?")
leia(litro)
escreva("entao vc gasta",km/litro)


Fimalgoritmo